# Generated by Django 5.1.7 on 2025-04-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Mixed', 'Mixed')], max_length=5),
        ),
    ]
