# Generated by Django 5.1.7 on 2025-04-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_event_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mixed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='start',
            field=models.TimeField(),
        ),
    ]
